title: Hello, world! I'm Juliano Saunders
description: > # this means to ignore newlines until "baseurl:"
  Hello, world! I'm Juliano Saunders, ill be blogging about tech, lifestyle, nerdy stuff and more!
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Juliano Saunders
author-img: juliano_saunders.jpg
about-author: I am a developer and wannabe blogger. 
social-twitter: akaJSaunders
social-facebook: juliano.saunders
social-github:  AkaJSaunders
social-linkedin: juliano-saunders
social-email: me@jsaunders.dev

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
